ALTER TABLE events ADD COLUMN position_x REAL NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN position_y REAL NOT NULL DEFAULT 0;
ALTER TABLE events ADD COLUMN position_set INTEGER NOT NULL DEFAULT 0;